spring:
 mvc:
  format:
    date-time: yyyy-MM-dd HH:mm:ss
 datasource:
   url: jdbc:postgresql://localhost:5432/logistic
   username: postgres
   password: Baracklekvar11
 jpa:
   show-sql: true
   hibernate:
    ddl-auto: create
  
